version: '3.8'

services:
  scraper:
    build: ./scrapy_sreality
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=anze
      - DB_PASSWORD=pass123
    depends_on:
      - db
    networks:
      - sreality_network

  server:
    build: ./server
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=anze
      - DB_PASSWORD=pass123
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - sreality_network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=anze
      - POSTGRES_PASSWORD=pass123
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - sreality_network
networks:
  sreality_network:
    driver: bridge
